name: expansion
description: The game Expansion

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.5 #https://pub.dev/packages/cupertino_icons
  flutter_bloc: ^8.0.1 #https://pub.dev/packages/flutter_bloc
  equatable: ^2.0.3 #https://pub.dev/packages/equatable
  flutter_svg: ^1.1.0 #https://pub.dev/packages/flutter_svg
  easy_localization: ^3.0.1 #https://pub.dev/packages/easy_localization
  flutter_native_splash: ^2.0.15 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.0.15  #https://pub.dev/packages/shared_preferences/install
  ocarina: ^0.1.2 #https://pub.dev/packages/ocarina
  flutter_launcher_icons: ^0.9.3 #https://pub.dev/packages/flutter_launcher_icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
# flutter pub run flutter_launcher_icons:main  
flutter_icons:
  flutter_test:
    sdk: flutter
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  # разрешение 1500*2346
  # image: assets/splash.png
  background_image: "assets/splash.png"
  # color: "0D2D54"


flutter:

  uses-material-design: true


assets:
  - assets
  - assets/svg/
  - assets/images/
  - assets/fonts/
  - assets/icons/
  - assets/translations/

fonts:
  - family: KellySlab
    fonts:
      - asset: fonts/KellySlab-Regular.ttf



