name: expansion
description: Space expansion
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=3.1.3 <4.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.5
    flutter_bloc: ^8.1.3
    equatable: ^2.0.5
    flutter_svg: ^2.0.7
    easy_localization: ^3.0.2
    flutter_native_splash: ^2.3.2
    shared_preferences: ^2.2.0
    audioplayers: ^5.1.0
    flutter_launcher_icons: ^0.13.1
    go_router: ^10.1.0
    google_fonts: ^5.1.0
    freezed_annotation: ^2.4.1
    animated_text_kit: ^4.2.2
    page_transition: ^2.0.9
    url_launcher: ^6.1.14
    computer: ^3.2.1
    json_annotation: ^4.8.1
    flutter_screenutil: ^5.8.4
    drop_cap_text: ^1.1.3
    confetti: ^0.7.0
    firebase_core: ^2.15.1
    google_sign_in: ^6.1.4
    flutter_svg_provider: ^1.0.6
    firebase_auth: ^4.7.3
    cloud_firestore: ^4.8.5
    get: ^4.6.5
    build_runner: ^2.4.6
    surf_lint_rules: ^3.0.0
    surf_logger: ^1.1.0
    bottom_sheet: ^4.0.0
    render_metrics: ^2.0.2
    surf_util: ^1.0.3
    sbp: ^0.0.8
    app_runner: ^2.2.0+1
dev_dependencies:
    flutter_test:
        sdk: flutter
    freezed: ^2.4.2
    json_serializable: ^6.7.1
flutter_icons:
    flutter_test:
        sdk: flutter
    android: launcher_icon
    ios: true
    image_path: assets/icon.png
flutter_native_splash:
    background_image: assets/splash.png
flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/icons/
        - assets/images/
        - assets/svg/
        - assets/fonts/
        - assets/translations/
        - assets/audio/
        - assets/scenes/
        - assets/images/asteroids/
        - assets/images/bases/
        - assets/images/explosion/
    fonts:
        -
            family: KellySlab
            fonts:
                -
                    asset: assets/fonts/KellySlab-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages