name: expansion
description: Space expansion

# 
# 
# space expansion
# Apple ID 
# flutter: 3.3.2

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5 #https://pub.dev/packages/cupertino_icons
  flutter_bloc: ^8.1.1 #https://pub.dev/packages/flutter_bloc
  equatable: ^2.0.5 #https://pub.dev/packages/equatable
  flutter_svg: ^1.1.4 #https://pub.dev/packages/flutter_svg
  easy_localization: ^3.0.1 #https://pub.dev/packages/easy_localization
  flutter_native_splash: ^2.2.8 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.0.15 #https://pub.dev/packages/shared_preferences/install
  ocarina: ^0.1.2 #https://pub.dev/packages/ocarina
  flutter_launcher_icons: ^0.10.0 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^5.0.3 #https://pub.dev/packages/go_router
  google_fonts: ^3.0.1 #https://pub.dev/packages/google_fonts
  freezed_annotation: ^2.1.0
  animated_text_kit: ^4.2.2 #https://pub.dev/packages/animated_text_kit
  page_transition: ^2.0.9 #https://pub.dev/packages/page_transition
  url_launcher: ^6.1.5 #https://pub.dev/packages/url_launcher
  # flame: ^1.3.0 #https://pub.dev/packages/flame
  # flame_audio: ^1.3.1 #https://pub.dev/packages/flame_audio

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.1 #https://pub.dev/packages/freezed
  build_runner: ^2.2.0 #https://pub.flutter-io.cn/packages/build_runner
  json_serializable: ^6.3.1 #https://pub.dev/packages/json_serializable
  # flutter pub run build_runner build
  # flutter pub run build_runner clean
  # flutter pub run build_runner build --delete-conflicting-outputs.


# flutter pub run flutter_launcher_icons:main
flutter_icons:
  flutter_test:
    sdk: flutter
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  # разрешение 1500*2346
  # image: assets/splash.png
  background_image: "assets/splash.png"
  # color: "0D2D54"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/
    - assets/audio/

  fonts:
    - family: KellySlab
      fonts:
        - asset: assets/fonts/KellySlab-Regular.ttf
