name: expansion
description: Space expansion
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.1.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 #https://pub.dev/packages/cupertino_icons
  flutter_bloc: ^8.1.3 #https://pub.dev/packages/flutter_bloc
  bloc: ^8.1.2  #https://pub.dev/packages/bloc
  equatable: ^2.0.5 #https://pub.dev/packages/equatable
  flutter_svg: ^2.0.7 #https://pub.dev/packages/flutter_svg
  easy_localization: ^3.0.3 #https://pub.dev/packages/easy_localization
  flutter_native_splash: ^2.3.4 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.2.2 #https://pub.dev/packages/shared_preferences
  audioplayers: ^5.2.0 #https://pub.dev/packages/audioplayers
  flutter_launcher_icons: ^0.13.1 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^12.0.0 #https://pub.dev/packages/go_router
  google_fonts: ^6.1.0 #https://pub.dev/packages/google_fonts
  freezed_annotation: ^2.4.1 #https://pub.dev/packages/freezed_annotation
  animated_text_kit: ^4.2.2 #https://pub.dev/packages/animated_text_kit
  page_transition: ^2.1.0 #https://pub.dev/packages/page_transition
  url_launcher: ^6.1.14 #https://pub.dev/packages/url_launcher
  computer: ^3.2.1 #https://pub.dev/packages/computer
  json_annotation: ^4.8.1 #https://pub.dev/packages/json_annotation
  flutter_screenutil: ^5.9.0 #https://pub.dev/packages/flutter_screenutil
  drop_cap_text: ^1.1.3 #https://pub.dev/packages/drop_cap_text
  confetti: ^0.7.0 #https:/cloud_firestore/pub.dev/packages/confetti
  google_sign_in: ^6.1.5 #https://pub.dev/packages/google_sign_in
  flutter_svg_provider: ^1.0.6 #https://pub.dev/packages/flutter_svg_provider
  get: ^4.6.6 #https://pub.dev/packages/get
  build_runner: ^2.4.6 #https://pub.dev/packages/build_runner
  surf_lint_rules: ^3.0.0 #https://pub.dev/packages/surf_lint_rules
  surf_logger: ^1.1.0 #https://pub.dev/packages/surf_logger
  bottom_sheet: ^4.0.0 #https://pub.dev/packages/bottom_sheet
  render_metrics: ^2.0.2 #https://pub.dev/packages/render_metrics
  # surf_util: ^1.0.3 #https://pub.dev/packages/surf_util
  sbp: ^0.0.8 #https://pub.dev/packages/sbp
  app_runner: ^2.2.0+1 #https://pub.dev/packages/app_runner
  popup_menu: ^2.0.0 #https://pub.dev/packages/popup_menu
  firebase_core: ^2.19.0 #https://pub.dev/packages/confetti
  firebase_auth: ^4.1.1 #https://pub.dev/packages/firebase_auth
  # cloud_firestore: ^4.0.4 #https://pub.dev/packages/cloud_firestore
  firebase_analytics: ^10.0.7 #https://pub.dev/packages/firebase_analytics
  firebase_crashlytics: ^3.4.0 #https://pub.dev/packages/firebase_crashlytics
  dio: ^5.3.3 #https://pub.dev/packages/dio
  talker_dio_logger: ^2.3.1 #https://pub.dev/packages/talker_dio_logger
  talker_flutter: ^3.5.3 #https://pub.dev/packages/talker_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
#   flutter pub run flutter_launcher_icons:main
flutter_icons:
  flutter_test:
    sdk: flutter
  android: launcher_icon
  ios: true
  image_path: assets/icon.png
#   flutter pub run flutter_native_splash:create
flutter_native_splash:
  background_image: assets/splash.png
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/
    - assets/audio/
    - assets/scenes/
    - assets/images/asteroids/
    - assets/images/bases/
    - assets/images/explosion/
  fonts:
    - family: KellySlab
      fonts:
        - asset: assets/fonts/KellySlab-Regular.ttf
