name: expansion
description: Space expansion

# 
# 
# space expansion
# Apple ID 
# flutter: 3.10
# com.example.expansion

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5 #https://pub.dev/packages/cupertino_icons
  flutter_bloc: ^8.1.3 #https://pub.dev/packages/flutter_bloc
  equatable: ^2.0.5 #https://pub.dev/packages/equatable
  flutter_svg: ^2.0.7 #https://pub.dev/packages/flutter_svg
  easy_localization: ^3.0.2 #https://pub.dev/packages/easy_localization
  flutter_native_splash: ^2.3.1 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.2.0 #https://pub.dev/packages/shared_preferences/install
  # assets_audio_player: ^3.0.6 #https://pub.dev/packages/assets_audio_player
  audioplayers: ^4.1.0 #https://pub.dev/packages/audioplayers
  flutter_launcher_icons: ^0.13.1 #https://pub.dev/packages/flutter_launcher_icons
  go_router: ^9.0.0 #https://pub.dev/packages/go_router
  google_fonts: ^4.0.1 #https://pub.dev/packages/google_fonts
  freezed_annotation: ^2.2.0 #https://pub.dev/packages/freezed_annotation
  animated_text_kit: ^4.2.2 #https://pub.dev/packages/animated_text_kit
  page_transition: ^2.0.9 #https://pub.dev/packages/page_transition
  url_launcher: ^6.1.11 #https://pub.dev/packages/url_launcher
  computer: ^3.2.1 #https://pub.dev/packages/computer
  json_annotation: ^4.8.1 # https://pub.flutter-io.cn/packages/json_annotation/install
  flutter_screenutil: ^5.8.4 # https://pub.dev/packages/flutter_screenutil
  drop_cap_text: ^1.1.3 #https://pub.dev/packages/drop_cap_text
  confetti: ^0.7.0 #https://pub.dev/packages/confetti
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.4 # https://pub.dev/packages/google_sign_in
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5 #https://pub.dev/packages/freezed
  build_runner: ^2.4.6 #https://pub.flutter-io.cn/packages/build_runner
  json_serializable: ^6.7.1 #https://pub.dev/packages/json_serializable
  # flutter pub run build_runner build --delete-conflicting-outputs.


# flutter pub run flutter_launcher_icons:main
flutter_icons:
  flutter_test:
    sdk: flutter
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  # разрешение 1500*2346
  # image: assets/splash.png
  background_image: "assets/splash.png"
  # color: "0D2D54"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/
    - assets/audio/
    - assets/scenes/
    - assets/images/asteroids/
    - assets/images/bases/
    - assets/images/explosion/
    
  fonts:
    - family: KellySlab
      fonts:
        - asset: assets/fonts/KellySlab-Regular.ttf
