// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13yZb0UzZRv1jw5r3XQP0NjgPTqSsvT0',
    appId: '1:847683646254:web:2ff3b6a38fd08e822300bf',
    messagingSenderId: '847683646254',
    projectId: 'expansion-1e30e',
    authDomain: 'expansion-1e30e-808e5.firebaseapp.com',
    storageBucket: 'expansion-1e30e.appspot.com',
    measurementId: 'G-B94JSJ5ZR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBETsw0ZH_hesX-O4LC1KjJaWFBXzbdWd8',
    appId: '1:847683646254:android:b312e2befe32060e2300bf',
    messagingSenderId: '847683646254',
    projectId: 'expansion-1e30e',
    storageBucket: 'expansion-1e30e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1pmhTAsFiq965gZAkuzzT1oQztz8iDk',
    appId: '1:847683646254:ios:8281d9f68a4bc2a02300bf',
    messagingSenderId: '847683646254',
    projectId: 'expansion-1e30e',
    storageBucket: 'expansion-1e30e.appspot.com',
    androidClientId:
        '847683646254-68po48b4niamtob1mh36snjf5l81im2f.apps.googleusercontent.com',
    iosClientId:
        '847683646254-vh620ojnps098ukg5mc6oltt75e2dvjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.expansion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1pmhTAsFiq965gZAkuzzT1oQztz8iDk',
    appId: '1:847683646254:ios:de776e811aa6451d2300bf',
    messagingSenderId: '847683646254',
    projectId: 'expansion-1e30e',
    storageBucket: 'expansion-1e30e.appspot.com',
    androidClientId:
        '847683646254-68po48b4niamtob1mh36snjf5l81im2f.apps.googleusercontent.com',
    iosClientId:
        '847683646254-47eov3fcbg1q2e82cpldn3io8m0g4rsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.expansion.RunnerTests',
  );
}
