// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCedRjDtZi0OucN5wFcQhE-ZcRUtBbeDic',
    appId: '1:962797678906:web:fbc06af0582c74b8dce003',
    messagingSenderId: '962797678906',
    projectId: 'space-expansion-8ac9a',
    authDomain: 'space-expansion-8ac9a.firebaseapp.com',
    storageBucket: 'space-expansion-8ac9a.appspot.com',
    measurementId: 'G-299DWNYZ6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWVlHPIds-JTFMYCTEzD6OGSHpWOOzj2o',
    appId: '1:962797678906:android:3b5b819a7564ee2adce003',
    messagingSenderId: '962797678906',
    projectId: 'space-expansion-8ac9a',
    storageBucket: 'space-expansion-8ac9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5ISKbfyXQ8u4AQvqZMmy5mHy7myjc8I',
    appId: '1:962797678906:ios:72f954fec014f07edce003',
    messagingSenderId: '962797678906',
    projectId: 'space-expansion-8ac9a',
    storageBucket: 'space-expansion-8ac9a.appspot.com',
    androidClientId: '962797678906-q5nibpqib9uvml664a2j2ls0i4js9mbb.apps.googleusercontent.com',
    iosClientId: '962797678906-2vvpicpadrqj4ne2vfk33jjp3q5crr4g.apps.googleusercontent.com',
    iosBundleId: 'com.ryjovs.expansion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe5ISKbfyXQ8u4AQvqZMmy5mHy7myjc8I',
    appId: '1:962797678906:ios:d2946eef9b20f6c4dce003',
    messagingSenderId: '962797678906',
    projectId: 'space-expansion-8ac9a',
    storageBucket: 'space-expansion-8ac9a.appspot.com',
    androidClientId: '962797678906-q5nibpqib9uvml664a2j2ls0i4js9mbb.apps.googleusercontent.com',
    iosClientId: '962797678906-ov423p2penol51ckmtmtv89fqjc0so5c.apps.googleusercontent.com',
    iosBundleId: 'com.ryjovs.expansion.RunnerTests',
  );
}
